apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-configmap
data:
  POSTGRES_USER: {{ .Values.login.username }}
  POSTGRES_DB: {{ .Values.login.database }}
  HOSTNAME: {{ .Values.login.hostname }}
